package ben.assignment5;

/**
 * Ben Hardy
 * 
 * 
 * CMPT 381
 * Assignment 5
 */


/**
 * Simple line model used for storing the properties of a line
 * Used for redrawing all lines after a drawing is done
 */
public class MyLine {

    /**
     * The start and end points of the line model
     */
    float x1, y1, x2, y2;

    /**
     * Simple autogenerated constructor for a basic line
     * @param x1 - the x coordinate of the start
     * @param y1 - the y coordinate of the start
     * @param x2 - the x coordinate of the end
     * @param y2 - the y coordinate of the end
     */
    public MyLine(float x1, float y1, float x2, float y2) {
        this.x1 = x1;
        this.y1 = y1;
        this.x2 = x2;
        this.y2 = y2;
    }
}
